### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by mbalamat** [RemoteControlHomeDevices/Refrigerator#2]
Sorry but I don't understand what do you mean at your README.md file
Thanks, for your time!

**Comment by thomas510111** [comment]
hello the project is not completed yet and we havent write the readme yet .If you are intrested in this project we can discusse it.
Ελληνας εισα?
Are you from greece?

**Comment by mbalamat** [comment]
Yes I am Greek but your project is international, also I am interested in home automation systems too, proceed and we will see...
Thank you,
